# Generated by Django 3.0.7 on 2020-06-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200622_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
