# Generated by Django 3.0.7 on 2020-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_events_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creation_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
