# Generated by Django 3.0.7 on 2020-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_events_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
