# Generated by Django 2.1.15 on 2020-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200703_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='events',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
